{"body": "\nLadybug component such as solar radiation analysis will subdivide the surface into smaller patches based on grid size specified.\n\n\n\nMay I ask how this is achieved using Python script, specifically the Rhinoscript commands used?\n\n\n\nThanks!\n", "attachments": [], "created_by_name": "Grasshope", "created_at": "September 15, 2015 at 11:03pm", "created_by": "Grasshope", "topic": "how to subdivide a surface using Python script?", "replies": [{"body": "\nDear buggers, advice is greatly appreciated! Thanks!\n", "attachments": [], "created_by_name": "Grasshope", "created_at": "September 18, 2015 at 1:57am", "created_by": "Grasshope", "replies": []}, {"body": "\nHi Grasshope,\n\n\n\nWhile I didn't write that component myself. You need the RhinoCommon Mesh.CreateFromBrep method\u00a0\n\nsearch\u00a0for it in the RhinoCommon - [http://4.rhino3d.com/5/rhinocommon/](http://4.rhino3d.com/5/rhinocommon/)\n\n\n\n\n\n\n\n\n\n[http://4.rhino3d.com/5/rhinocommon/](http://4.rhino3d.com/5/rhinocommon/)\n", "attachments": [], "created_by_name": "Anton Szilasi", "created_at": "September 18, 2015 at 7:30am", "created_by": "AntonSzilasi", "replies": [{"body": "\nHi Grasshoppe,\n\nAnton is right. You just need to set a number of meshing parameters based on the gridSize.\n\nHere is the sample code that you can find in Honeybee_Generate Test Points:\n\n[https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeyb...](https://github.com/mostaphaRoudsari/Honeybee/blob/master/src/Honeybee_Generate%20Test%20Points.py#L57-L78)\n\nMostapha\n", "attachments": [], "created_by_name": "Mostapha Sadeghipour Roudsari", "created_at": "September 22, 2015 at 4:32pm", "created_by": "MostaphaSadeghipour", "replies": []}, {"body": "\nThank you Anton and Mostapha!\n\n\n\nI did a brute force \"copy and paste\" test of the following code, and it didn't work with the warning of unable to determine the length of the brep objects.\n\n\n\nI'm sure I get it wrong in this way, and I hope you can point out how to correct the errors.\n\n\n\n**import Rhino as rc**<br/>**import Grasshopper.Kernel as gh**<br/>**from itertools import chain**<br/>**import System.Threading.Tasks as tasks**<br/>**import rhinoscriptsyntax as rs**<br/><br/>**mesh = []**<br/><br/>**def createMesh(brep, gridSize):**<br/>**\u00a0\u00a0\u00a0 ## mesh breps**<br/>**\u00a0\u00a0\u00a0 def makeMeshFromSrf(i, inputBrep):**<br/>**\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 try:**<br/>**\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 mesh[i] = rc.Geometry.Mesh.CreateFromBrep(inputBrep, meshParam)[0]**<br/>**\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 inputBrep.Dispose()**<br/>**\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 except:**<br/>**\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 print 'Error in converting Brep to Mesh...'**<br/>**\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0 pass**<br/><br/>**\u00a0\u00a0\u00a0 # prepare bulk list for each surface**<br/>**\u00a0\u00a0\u00a0 mesh = [None] * len(brep)**<br/><br/>**\u00a0\u00a0\u00a0 # set-up mesh parameters for each surface based on surface size**<br/>**\u00a0\u00a0\u00a0 meshParam = rc.Geometry.MeshingParameters.Default**<br/>**\u00a0\u00a0\u00a0 meshParam.MaximumEdgeLength = gridSize**<br/>**\u00a0\u00a0\u00a0 meshParam.MinimumEdgeLength = gridSize**<br/>**\u00a0\u00a0\u00a0 meshParam.GridAspectRatio = 1**<br/><br/>**\u00a0\u00a0\u00a0 for i in range(len(mesh)): makeMeshFromSrf(i, brep[i])**<br/>**\u00a0\u00a0 \u00a0**<br/>**\u00a0\u00a0\u00a0 return mesh**<br/><br/>**createMesh(brep, 0.1)**\n\n\n\n**[<img class=\"align-full\" src=\"http://api.ning.com:80/files/3FLLVGZOVWKgrsKz5nbkZaNHoQiTNy0nx98UOAWlrmWVKYs*gANWntmCHEsHVH96kOiOUp5k73Aad6pN2UCvEGWdcFnS*h8L/Capture.PNG?width=721\" width=\"721\"/>](http://api.ning.com:80/files/3FLLVGZOVWKgrsKz5nbkZaNHoQiTNy0nx98UOAWlrmWVKYs*gANWntmCHEsHVH96kOiOUp5k73Aad6pN2UCvEGWdcFnS*h8L/Capture.PNG)**\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1366877", "name": "brepToMesh_v001.gh"}], "created_by_name": "Grasshope", "created_at": "September 22, 2015 at 9:20pm", "created_by": "Grasshope", "replies": []}, {"body": "\nGrasshope,\n\nMake sure you have input parameter \"brep\" set to 'List Access' and Type Hint 'Brep' (see screen capture below). I've also added a \"gridSize\" input parameter so you can control the number of mesh faces.\n\nHope this helps.\n\n/SPM\n\n[<img class=\"align-full\" src=\"http://api.ning.com:80/files/XV4h3WhRBOFgqTbVuyRJpnxXaSwMrKHcuiu0l9etar3CmeWw4KBY8gZcbs8ND5NwqGYaSTc9*XAaPJsEwKDuBvicfyr0AaBe/brepToMesh.png?width=721\" width=\"721\"/>](http://api.ning.com:80/files/XV4h3WhRBOFgqTbVuyRJpnxXaSwMrKHcuiu0l9etar3CmeWw4KBY8gZcbs8ND5NwqGYaSTc9*XAaPJsEwKDuBvicfyr0AaBe/brepToMesh.png)\n", "attachments": [], "created_by_name": "Stephen Maher", "created_at": "September 23, 2015 at 7:32am", "created_by": "StephenPMaher", "replies": []}, {"body": "\nFile attached.\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1367322", "name": "brepToMesh_v001_SPM.gh"}], "created_by_name": "Stephen Maher", "created_at": "September 23, 2015 at 7:33am", "created_by": "StephenPMaher", "replies": []}, {"body": "\nThank very much, Stephen!\n\n\n\nI found that unexploded Brep object will not be properly processed by the code: only the first surface within the Brep object will be converted to a mesh.\n\n\n\nCan you kindly advise the rhinoscript to explode a Brep surface?\n\n\n\nThank you!\n\n\n\n[<img class=\"align-full\" src=\"http://api.ning.com:80/files/viirmOBcoEG8nTbwb3U0FWrxcmPuFskHwRF487dG-bwnKRbV1-fjVMxdoHCDwDMb1t1WA-YjSC8AoudpgUyj6xYAwoJHr8ky/Capture.PNG?width=721\" width=\"721\"/>](http://api.ning.com:80/files/viirmOBcoEG8nTbwb3U0FWrxcmPuFskHwRF487dG-bwnKRbV1-fjVMxdoHCDwDMb1t1WA-YjSC8AoudpgUyj6xYAwoJHr8ky/Capture.PNG)\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1370925", "name": "GhPython_v005.gh"}], "created_by_name": "Grasshope", "created_at": "September 29, 2015 at 11:46pm", "created_by": "Grasshope", "replies": []}, {"body": "\nThe easiest solution is to use the [Deconstruct Brep] component and plug in the output faces into Python. You would have to do this for the [Honeybee_Generate Test Points] component as well.\n\nConcerning your second question below, that has to do with the way we call the function. In the Honeybee component, you will notice that Mostapha creates a new list from 'createMesh' and passes that through another function as an argument. So the organization is a bit different from what you're doing.\n\nHope this helps.\n\n/SPM\n", "attachments": [], "created_by_name": "Stephen Maher", "created_at": "September 30, 2015 at 12:32pm", "created_by": "StephenPMaher", "replies": []}, {"body": "\nHi Grasshope\n\n\n\nIs this what you are looking for? Check out the component Brep to Mesh\n\n\n\nCheers,\n\n\n\nAnton\n", "attachments": [{"link": "http://www.grasshopper3d.com/group/ladybug/forum/attachment/download?id=2985220%3AUploadedFile%3A1371102", "name": "BreptoMesh AJZ 30.9.2015.gh"}], "created_by_name": "Anton Szilasi", "created_at": "September 30, 2015 at 12:47pm", "created_by": "AntonSzilasi", "replies": []}, {"body": "\nHi Stephen,\u00a0\n\n\n\nI also wonder why in your GH file the **brep** node must be set as \"List Access\" to take a group of Breps, whereas in Mostapha's **Honeybee_Generate Test Points** component, the **_testSurface** node set as \"Item Access\" can take a group of Brep as input using the same Python code...\n\n\n", "attachments": [], "created_by_name": "Grasshope", "created_at": "September 30, 2015 at 9:55am", "created_by": "Grasshope", "replies": []}]}], "id": "1362546"}